[project]
name = "exponentials"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "casadi>=3.7.2",
    "ipykernel>=6.30.1",
    "matplotlib>=3.10.6",
]
