[project]
name = "exponentials"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10, <3.12"
dependencies = [
    "casadi>=3.7.2",
    "insideopt-seeker>=0.1.21",
    "ipykernel>=6.30.1",
    "matplotlib>=3.10.6",
    "setuptools>=80.9.0",
]
